PLOVER:
  temp_path: "~/Desktop/bccdc/ViroReportR/dat_test/plover_weekly_resp.rds"
  bccdc_path: ""

PHRDW:
  temp_path: "~/Desktop/bccdc/ViroReportR/dat_test/phrdw_flu_daily_count_vpp_only.rData"
  bccdc_path: ""

zero_threshold: 0.50

min_nb_cases_flua: 11
min_nb_cases_flub: 11
min_nb_cases_rsv: 11
min_nb_cases_covid: 8

vri_names: ['Influenza-A', 'Influenza-B', "SARS-CoV-2", "RSV"]
